name: emrobostack-kernel
channels:
  - /home/michael/micromamba/envs/emscripten-forge/conda-bld
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge 
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - ipython=8.14
  - ipycanvas
  - ipywidgets
  - jupyterlab_widgets
  - ros-humble-osrf-testing-tools-cpp
  - ros-humble-rcutils
  - ros-humble-rclpy
  - ros-humble-rosidl-parser
  - ros-humble-std-msgs
  - ros-humble-wasm-cpp
  - ros-humble-rmw-wasm-cpp
  - ros2-distro-mutex=0.5.*
